### ISSUE TITLE
react-router 4

### ISSUE THREAD

**Issue by 4ware** [benawad/react-menu-monkey-client#4]
How about updating the code for version 4 of the router?

**Comment by benawad** [comment]
What should I be doing differently in version 4? I believe the code is still compatible.

**Comment by 4ware** [comment]
Nope. I accidentally installed v4 with 'yarn add' and it's not running since nesting routes is handled differently.

**Comment by benawad** [comment]
Oh got it. I think I am going to do a whole revamp of the project and upgrade it to all the latest stuff.

**Comment by 4ware** [comment]
Thanks! That would be great!

**Comment by benawad** [comment]
Thanks for bringing it to my attention!

**Comment by benawad** [comment]
I updated the code and there will be some YouTube videos coming out later this month on how I upgraded the code.

**Comment by 4ware** [comment]
Thanks a lot!
